<?php

function usagov_wizards_theme($existing, $type, $theme, $path) {
    return [
        'usagov_wizards_wizard' => [
            'variables' => [
                'hello' => t('Hello World!'),
                'wizard_tree' => [],
                'wizard_step_form' => ''
            ],
        ],
        'usagov_wizards_wizard_select' => [
            'variables' => [
                'hello' => t('Hello World!'),
                'wizards' => []
            ],
        ],
    ];
}

// function usagov_wizards_theme() {
//     $routeName = \Drupal::routeMatch()->getRouteName();
    
//     if ( $routeName === 'usagov_wizards.wizards' ) {
//         $theme['usagov_wizards_wizards'] = [
//             'template' => 'page--select-wizard',
//             'variables' => [
//                 'hello' => 'hello world',
//             ],
//         ];
//         $theme['page__select_wizard'] = [
//             'template' => 'page--select-wizard',
//         ];
//     } else if ( $routeName === 'usagov_wizards.wizards.wizard' ) {
//         $wizardId = \Drupal::routeMatch()->getParameter('wizard_id');
//         $theme['usagov_wizards_wizard'] = [
//             'template' => 'page--wizard',
//             'variables' => [
//                 'hello' => 'hello world',
//             ],
//         ];
//         $theme['page__wizard'] = [
//             'template' => 'page--wizard',
//         ];
//     }

//     return $theme;
// }